### ISSUE TITLE
exoplayer Invalid descriptor: ex

### ISSUE THREAD

**Issue by jw3** [jw3/mvf2#16]
```
    Caused by: java.lang.BootstrapMethodError: Exception from call site #96 bootstrap method
        at com.google.android.exoplayer2.ui.PlayerControlView.<init>(PlayerControlView.java:293)
        at com.google.android.exoplayer2.ui.PlayerView.<init>(PlayerView.java:452)
        at com.google.android.exoplayer2.ui.PlayerView.<init>(PlayerView.java:304)
        	... 35 more
     Caused by: java.lang.NoClassDefFoundError: Invalid descriptor: ex
```

**Comment by jw3** [comment]
add
```
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
```
